CREATE TABLE [dbo].[cdCstmrItmBllble]
(
	[Id] INT NOT NULL PRIMARY KEY,
	 [documentNumber] TEXT NOT NULL,
        [description] TEXT NOT NULL,
        [externalReference] TEXT NOT NULL,
        [invoiceDate] TEXT NOT NULL,
        [postingDate] TEXT NOT NULL,
        [invoiceOrCreditMemo] TEXT NOT NULL,
        [buyer] TEXT NOT NULL,
        [billTo] TEXT NOT NULL,
        [salesUnit] TEXT NOT NULL,
        [itemDescription] TEXT NOT NULL,
        [itemQuantity] TEXT NOT NULL,
        [unitCode] TEXT NOT NULL,
        [itemUnitPrice] INT NOT NULL,
        [currencyCode] TEXT NOT NULL,
        [itemTaxCode] TEXT NOT NULL,
        [countryCode] TEXT NOT NULL,
        [itemAccAssignType] TEXT NOT NULL,
        [itemProTaskID] TEXT NOT NULL,
        [provider] TEXT NOT NULL,
        [itemProduct] TEXT NOT NULL,
        [stts] TEXT NOT NULL,
        [pmntMthd] TEXT NOT NULL
)
